package com.newoether.agora.viewmodel

import com.newoether.agora.model.ChatMessage
import com.newoether.agora.model.Participant
import com.newoether.agora.util.Constants
import org.junit.Assert.assertEquals
import org.junit.Test
import java.util.Calendar

class GenerationManagerUserTemplateTest {
    @Test
    fun applyUserTemplateToMessages_formatsSentDateWithEnglishWeekday() {
        val sentAt = Calendar.getInstance().apply {
            clear()
            set(2026, Calendar.MAY, 9, 12, 34, 56)
        }.timeInMillis
        val messages = listOf(
            ChatMessage(id = "u1", text = "hello", participant = Participant.USER, timestamp = sentAt),
        )

        val result = applyUserTemplateToMessages(
            messages,
            "<sent date=\"{sent_date}\" time=\"{sent_time}\">",
            null,
        )

        assertEquals("<sent date=\"2026-05-09 Sat\" time=\"12:34:56\">hello", result.single().text)
    }

    @Test
    fun applyUserTemplateToMessages_wrapsOnlyNormalUserMessages() {
        val messages = listOf(
            ChatMessage(id = "u1", text = "hello", participant = Participant.USER),
            ChatMessage(id = Constants.RESULT_MSG_PREFIX + "r1", text = "tool output", participant = Participant.USER),
            ChatMessage(id = Constants.TOOL_MSG_PREFIX + "t1", text = "", participant = Participant.MODEL),
            ChatMessage(id = "m1", text = "assistant", participant = Participant.MODEL)
        )

        val result = applyUserTemplateToMessages(messages, "<wrap>", "</wrap>")

        assertEquals("<wrap>hello</wrap>", result[0].text)
        assertEquals("tool output", result[1].text)
        assertEquals("", result[2].text)
        assertEquals("assistant", result[3].text)
    }

    @Test
    fun exactInputProjectionAppliesTemplatesAndRelocatesAssistantImagesOnce() {
        val messages = listOf(
            ChatMessage(
                id = "assistant-image",
                text = "generated",
                images = listOf("generated.png"),
                participant = Participant.MODEL,
            ),
            ChatMessage(id = "latest-user", text = "inspect", participant = Participant.USER),
        )

        val projected = projectGenerationInputMessages(
            messages = messages,
            includeImages = true,
            userPrepend = "<",
            userPostpend = ">",
        )

        assertEquals(emptyList<String>(), projected[0].images)
        assertEquals(listOf("generated.png"), projected[1].images)
        assertEquals(
            "<[Visual context: the first attached image was generated by the assistant earlier in this conversation.]\n\ninspect>",
            projected[1].text,
        )
    }

    @Test
    fun nonVisionProjectionRemovesEveryRawImageFromAccountingAndDispatch() {
        val messages = listOf(
            ChatMessage(
                id = "user",
                text = "described attachment",
                images = listOf("attachment.png"),
                participant = Participant.USER,
            ),
            ChatMessage(
                id = Constants.RESULT_MSG_PREFIX + "result",
                text = "tool result",
                images = listOf("tool.png"),
                participant = Participant.USER,
            ),
        )

        val projected = projectGenerationInputMessages(
            messages = messages,
            includeImages = false,
            userPrepend = null,
            userPostpend = null,
        )

        assertEquals(emptyList<String>(), projected.flatMap { it.images })
        assertEquals("described attachment", projected.first().text)
    }

    @Test
    fun compactInvocationIsAnApiOnlyFinalUserMessage() {
        val durableMessages = listOf(
            ChatMessage(id = "user", text = "question", participant = Participant.USER),
            ChatMessage(id = "assistant", text = "answer", participant = Participant.MODEL),
        )

        val projected = projectGenerationInputMessages(
            messages = durableMessages,
            includeImages = true,
            userPrepend = null,
            userPostpend = null,
            initialUserPrompt = "Create the compact context summary now.",
        )

        assertEquals(durableMessages, projected.dropLast(1))
        assertEquals(Participant.USER, projected.last().participant)
        assertEquals("Create the compact context summary now.", projected.last().text)
        assertEquals("assistant", projected.last().parentId)
    }
}
